# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('crated_by', models.DateTimeField(default=django.utils.timezone.now)),
                ('topic', models.CharField(max_length=100, verbose_name='Tópico')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.House', verbose_name='Casa correspondente')),
            ],
        ),
    ]
