# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuator',
            name='actuator_type',
            field=models.IntegerField(choices=[(1, 'Lâmpada'), (2, 'Sonar'), (3, 'Temperatura'), (4, 'Ventilador')], default=1),
        ),
    ]
