# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuator', '0002_actuator_actuator_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuator',
            name='description',
            field=models.CharField(default=1, max_length=100, verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
