# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuator', '0003_actuator_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator',
            name='actuator_type',
            field=models.IntegerField(choices=[(1, 'Lâmpada'), (2, 'Sonar'), (3, 'Temperatura'), (4, 'Ventilador'), (5, 'Outro')], default=1),
        ),
    ]
