# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 04:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('crated_by', models.DateTimeField(default=django.utils.timezone.now)),
                ('server', models.CharField(max_length=100, verbose_name='Servidor')),
                ('user', models.CharField(max_length=100, verbose_name='Usuário')),
                ('password', models.CharField(max_length=100, verbose_name='Senha')),
                ('portws', models.CharField(max_length=100, verbose_name='Porta para websocket')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
            ],
        ),
    ]
