# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20170608_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
    ]
