# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='crated_by',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
