# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_house_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='hash_key',
            field=models.CharField(default='e3238b2e', max_length=100, verbose_name='Chave de acesso'),
        ),
    ]
