# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_house_hash_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='hash_key',
            field=models.CharField(default='d6842313', max_length=100, verbose_name='Chave de acesso'),
        ),
    ]
