# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0010_auto_20170617_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='house',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='house',
            name='hash_key',
            field=models.CharField(default='9a90d36d', max_length=100, verbose_name='Chave de acesso'),
        ),
    ]
